version: '3'
    
services:
    app-core:
        build: 
            # -- Directory containing Dockerfile, or url to a git repository --
            context: .

        command: python manage.py runserver 0.0.0.0:8000

        volumes: 
            - .:/app
            
        ports:
            - "8000:8000"